### ISSUE TITLE
Not hiding content injected using include plugin

### ISSUE THREAD

**Issue by emilracec** [mittelab/ifauthex-dokuwiki-plugin#6] opened 2020-08-27 10:46 UTC
Hi guys,

I've just switched from ifauth to ifauthex and noticed that the new plugin is not working when trying to hide content added to the page using include plugin (https://www.dokuwiki.org/plugin:include). This is a very popular plugin - could you please fix the integration of ifatuhex with it?

I also attach an example:
<ifauth !@admin>
not see this // --> this content is correctly hidden from admins
{{section>:another_ns:page#section}} // --> this content is not hidden from admins
</ ifauth>

Thank you.

**Comment by 5p4k** [comment] 2023-02-08 13:29
I cannot reproduce this, your example works with the current version (on Igor).
I'll close this for now. It could be that it got fixed with newer versions of the plugin or Dokuwiki.

**Closed as completed by 5p4k** 2023-02-08 13:29 UTC
Labels: enhancement
